service: math-refresher

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${opt:stage, 'dev'}
  environment:
    MONGO_URI: ${file(./.env):${self:provider.stage}.MONGO_URI}

# you can define service wide environment variables here
#  environment:
#    variable1: value1

  exclude:
    - .git/**
    - data/**
    - docs/**

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: test
          method: get

